const mongoose = require('mongoose');

const drivingDeskCheckSheetSchema = new mongoose.Schema({
  // SMI Section
  smi_1_actual: String,
  smi_2_actual: String,
  smi_3_actual: String,
  
  // Modification Section
  modification_1_actual: String,
  modification_2_actual: String,
  modification_3_actual: String,
  modification_4_actual: String,
  modification_5_actual: String,
  modification_6_actual: String,
  modification_7_actual: String,
  modification_8_actual: String,
  modification_9_actual: String,
  
  // TC/T1 Section
  tc_t1_1_actual: String,
  
  // Supervisor Signature
  supervisor_signature: String,
  
  // Must Change Items
  must_change_1_actual: String,
  must_change_2_actual: String,
  must_change_3_actual: String,
  must_change_4_actual: String,
  must_change_5_actual: String,
  must_change_6_actual: String,
  must_change_7_actual: String,
  must_change_8_actual: String,
  must_change_9_actual: String,
  must_change_10_actual: String,
  must_change_11_actual: String,
  must_change_12_actual: String,
  must_change_13_actual: String,
  must_change_14_actual: String,
  must_change_15_actual: String,
  must_change_16_actual: String,
  must_change_17_actual: String,
  must_change_18_actual: String,
  must_change_19_actual: String,
  must_change_20_actual: String,
  must_change_21_actual: String,
  must_change_22_actual: String,
  must_change_23_actual: String,
  must_change_24_actual: String,
  must_change_25_actual: String,
  must_change_26_actual: String,
  must_change_27_actual: String,
  must_change_28_actual: String,
  
  // Driver Desk Panel
  driver_desk_1_1_actual: String,
  driver_desk_1_2_actual: String,
  driver_desk_2_1_actual: String,
  driver_desk_2_2_actual: String,
  driver_desk_3_1_actual: String,
  driver_desk_3_2_actual: String,
  driver_desk_4_1_actual: String,
  driver_desk_4_2_actual: String,
  driver_desk_6_1_actual: String,
  driver_desk_6_2_actual: String,
  driver_desk_7_1_actual: String,
  driver_desk_7_2_actual: String,
  driver_desk_8_1_actual: String,
  driver_desk_8_2_actual: String,
  driver_desk_9_1_actual: String,
  driver_desk_9_2_actual: String,
  driver_desk_10_1_actual: String,
  driver_desk_10_2_actual: String,
  driver_desk_11_1_actual: String,
  driver_desk_11_2_actual: String,
  driver_desk_12_1_actual: String,
  driver_desk_12_2_actual: String,
  driver_desk_13_1_actual: String,
  driver_desk_13_2_actual: String,
  
  // BL Box
  check_operation_of_levers_desk1: String,
  check_operation_of_levers_desk2: String,
  check_operation_of_ht_switches_without_bl_key_desk1: String,
  check_operation_of_ht_switches_without_bl_key_desk2: String,
  check_operation_of_ht_switches_with_bl_key_desk1: String,
  check_operation_of_ht_switches_with_bl_key_desk2: String,
  check_closing_opening_limit_switches_desk1: String,
  check_closing_opening_limit_switches_desk2: String,
  when_contacts_are_closed_desk1: String,
  when_contacts_are_closed_desk2: String,
  when_contacts_are_opened_desk1: String,
  when_contacts_are_opened_desk2: String,
  check_limit_switch_separators_for_any_breakage_crack_desk1: String,
  check_limit_switch_separators_for_any_breakage_crack_desk2: String,
  check_the_bl_box_bulb_holder_desk1: String,
  check_the_bl_box_bulb_holder_desk2: String,
  
  // Limit Switch
  free_operation_of_lever_desk1: String,
  free_operation_of_lever_desk2: String,
  closing_and_opening_of_limit_switch_desk1: String,
  closing_and_opening_of_limit_switch_desk2: String,
  continuity_checking_when_contact_closed_desk1: String,
  continuity_checking_when_contact_closed_desk2: String,
  open_circuit_when_contact_open_desk1: String,
  open_circuit_when_contact_open_desk2: String,
  check_for_any_crack_and_damage_desk1: String,
  check_for_any_crack_and_damage_desk2: String,
  
  // ZPT / BL Switch
  check_switch_body_zpt: String,
  check_switch_body_bl: String,
  check_operating_mechanism_zpt: String,
  check_operating_mechanism_bl: String,
  check_condition_of_contacts_zpt: String,
  check_condition_of_contacts_bl: String,
  check_the_opening_of_contacts_on_slight_movement_of_operating_mechanism_desk1: String,
  check_the_opening_of_contacts_on_slight_movement_of_operating_mechanism_desk2: String,
  ir_value_with_500v_megger_zpt: String,
  ir_value_with_500v_megger_bl: String,
  contact_to_contact_zpt: String,
  contact_to_contact_bl: String,
  contact_to_body_earth_zpt: String,
  contact_to_body_earth_bl: String,
  check_for_good_contact_pressure_zpt: String,
  check_for_good_contact_pressure_bl: String,
  check_closing_opening_sequence_of_contacts_as_per_programme_diagram_desk1: String,
  check_closing_opening_sequence_of_contacts_as_per_programme_diagram_desk2: String,
  
  // Master Controller
  check_drum_teeth_cam_roller_mp1: String,
  check_drum_teeth_cam_roller_mp2: String,
  check_sleeves_cable_crimping_mp1: String,
  check_sleeves_cable_crimping_mp2: String,
  grease_inter_locking_discs_mp1: String,
  grease_inter_locking_discs_mp2: String,
  check_interlock_mechanism_mp1: String,
  check_interlock_mechanism_mp2: String,
  check_mechanical_locking_mp1: String,
  check_mechanical_locking_mp2: String,
  check_contact_gap_mp1: String,
  check_contact_gap_mp2: String,
  check_contact_pressure_mp1: String,
  check_contact_pressure_mp2: String,
  check_cam_switches_mp1: String,
  check_cam_switches_mp2: String,
  check_insulation_resistance_mp1: String,
  check_insulation_resistance_mp2: String,
  check_indication_plates_mp1: String,
  check_indication_plates_mp2: String,
  check_handles_condition_mp1: String,
  check_handles_condition_mp2: String,
  check_condenser_value_mp1: String,
  check_condenser_value_mp2: String,
  check_resistance_value_mp1: String,
  check_resistance_value_mp2: String,
  check_spring_condition_mp1: String,
  check_spring_condition_mp2: String,
  
  // Push Button
  check_body_crack_damage_bpp1: String,
  check_body_crack_damage_bpp2: String,
  check_body_crack_damage_bpr1: String,
  check_body_crack_damage_bpr2: String,
  check_body_crack_damage_bpt1: String,
  check_body_crack_damage_bpt2: String,
  check_body_crack_damage_bpqd1: String,
  check_body_crack_damage_bpqd2: String,
  check_contact_fixed_firmly_bpp1: String,
  check_contact_fixed_firmly_bpp2: String,
  check_contact_fixed_firmly_bpr1: String,
  check_contact_fixed_firmly_bpr2: String,
  check_contact_fixed_firmly_bpt1: String,
  check_contact_fixed_firmly_bpt2: String,
  check_contact_fixed_firmly_bpqd1: String,
  check_contact_fixed_firmly_bpqd2: String,
  check_contacts_flash_pitting_bpp1: String,
  check_contacts_flash_pitting_bpp2: String,
  check_contacts_flash_pitting_bpr1: String,
  check_contacts_flash_pitting_bpr2: String,
  check_contacts_flash_pitting_bpt1: String,
  check_contacts_flash_pitting_bpt2: String,
  check_contacts_flash_pitting_bpqd1: String,
  check_contacts_flash_pitting_bpqd2: String,
  check_operation_push_button_bpp1: String,
  check_operation_push_button_bpp2: String,
  check_operation_push_button_bpr1: String,
  check_operation_push_button_bpr2: String,
  check_operation_push_button_bpt1: String,
  check_operation_push_button_bpt2: String,
  check_operation_push_button_bpqd1: String,
  check_operation_push_button_bpqd2: String,
  check_continuity_discontinuity_bpp1: String,
  check_continuity_discontinuity_bpp2: String,
  check_continuity_discontinuity_bpr1: String,
  check_continuity_discontinuity_bpr2: String,
  check_continuity_discontinuity_bpt1: String,
  check_continuity_discontinuity_bpt2: String,
  check_continuity_discontinuity_bpqd1: String,
  check_continuity_discontinuity_bpqd2: String,
  check_insulation_resistance_contact_bpp1: String,
  check_insulation_resistance_contact_bpp2: String,
  check_insulation_resistance_contact_bpr1: String,
  check_insulation_resistance_contact_bpr2: String,
  check_insulation_resistance_contact_bpt1: String,
  check_insulation_resistance_contact_bpt2: String,
  check_insulation_resistance_contact_bpqd1: String,
  check_insulation_resistance_contact_bpqd2: String,
  
  // Additional Push Button Components
  check_body_crack_damage_bpsw1: String,
  check_body_crack_damage_bpsw2: String,
  check_body_crack_damage_sw1: String,
  check_body_crack_damage_sw2: String,
  check_body_crack_damage_bpqwc1: String,
  check_body_crack_damage_bpqwc2: String,
  check_contact_fixed_firmly_bpsw1: String,
  check_contact_fixed_firmly_bpsw2: String,
  check_contact_fixed_firmly_sw1: String,
  check_contact_fixed_firmly_sw2: String,
  check_contact_fixed_firmly_bpqwc1: String,
  check_contact_fixed_firmly_bpqwc2: String,
  check_contacts_flash_pitting_bpsw1: String,
  check_contacts_flash_pitting_bpsw2: String,
  check_contacts_flash_pitting_sw1: String,
  check_contacts_flash_pitting_sw2: String,
  check_contacts_flash_pitting_bpqwc1: String,
  check_contacts_flash_pitting_bpqwc2: String,
  check_operation_push_button_bpsw1: String,
  check_operation_push_button_bpsw2: String,
  check_operation_push_button_sw1: String,
  check_operation_push_button_sw2: String,
  check_operation_push_button_bpqwc1: String,
  check_operation_push_button_bpqwc2: String,
  check_continuity_discontinuity_bpsw1: String,
  check_continuity_discontinuity_bpsw2: String,
  check_continuity_discontinuity_sw1: String,
  check_continuity_discontinuity_sw2: String,
  check_continuity_discontinuity_bpqwc1: String,
  check_continuity_discontinuity_bpqwc2: String,
  check_insulation_resistance_contact_bpsw1: String,
  check_insulation_resistance_contact_bpsw2: String,
  check_insulation_resistance_contact_sw1: String,
  check_insulation_resistance_contact_sw2: String,
  check_insulation_resistance_contact_bpqwc1: String,
  check_insulation_resistance_contact_bpqwc2: String
}, {
  timestamps: true
});

module.exports = mongoose.model('drivingDeskCheckSheet', drivingDeskCheckSheetSchema);