const mongoose = require('mongoose');

// Define the Panel Shop Check Sheet schema with all specific fields
const panelShopCheckSheetSchema = new mongoose.Schema({
  // SMI/MS of BA Panel
  status2: String,
  status3: String,
  status4: String,
  status5: String,
  status6: String,
  status7: String,
  status8: String,
  status9: String,
  status10: String,

  // Reverser System fields
  rs_1_11: String,
  yiuy: String,
  rs_1_21: String,
  uiyu: String,
  rs_1_31: String,
  iyui: String,
  rs_1_41: String,
  yiu: String,
  rs_1_51: String,
  yi: String,
  rs_1_61: String,
  yiuyi: String,
  rs_1_12: String,
  rs_1_22: String,
  rs_1_32: String,
  rs_1_42: String,
  rs_1_52: String,
  rs_1_62: String,
  rs_2_12: String,
  rs_2_22: String,
  rs_2_32: String,
  rs_2_42: String,
  rs_2_52: String,
  rs_2_62: String,
  rs_2_13: String,
  rs_2_23: String,
  rs_2_33: String,
  rs_2_43: String,
  rs_2_53: String,
  rs_2_63: String,
  rs_3_13: String,
  rs_3_23: String,
  rs_3_33: String,
  rs_3_43: String,
  rs_3_53: String,
  rs_3_63: String,
  rs_3_14: String,
  rs_3_24: String,
  rs_3_34: String,
  rs_3_44: String,
  rs_3_54: String,
  rs_3_64: String,
  rs_4_14: String,
  rs_4_24: String,
  rs_4_34: String,
  rs_4_44: String,
  rs_4_54: String,
  rs_4_64: String,
  rs_5: String,
  rs_6: String,
  rs_7: String,
  rs_8: String,
  rs_9: String,
  rs_10: String,
  rs_11: String,
  rs_12: String,
  rs_13: String,

  // CTF fields
  ctf1_1: String,
  ctf2_1: String,
  ctf3_1: String,
  ctf1_2: String,
  ctf2_2: String,
  ctf3_2: String,
  ctf1_3: String,
  ctf2_3: String,
  ctf3_3: String,
  ctf1_4: String,
  ctf2_4: String,
  ctf3_4: String,
  ctf1_5: String,
  ctf2_5: String,
  ctf3_5: String,
  ctf1_6: String,
  ctf2_6: String,
  ctf3_6: String,
  ctf1_7: String,
  ctf2_7: String,
  ctf3_7: String,
  ctf1_8: String,
  ctf2_8: String,
  ctf3_8: String,
  ctf1_9: String,
  ctf2_9: String,
  ctf3_9: String,
  ctf1_10: String,
  ctf2_10: String,
  ctf3_10: String,
  ctf1_11: String,
  ctf2_11: String,
  ctf3_11: String,
  ctf1_12: String,
  ctf2_12: String,
  ctf3_12: String,
  ctf1_13: String,
  ctf2_13: String,
  ctf3_13: String,
  ctf1_14: String,
  ctf2_14: String,
  ctf3_14: String,
  ctf1_15: String,
  ctf2_15: String,
  ctf3_15: String,
  ctf1_16: String,
  ctf2_16: String,
  ctf3_16: String,
  ctf1_17: String,
  ctf2_17: String,
  ctf3_17: String,
  ctf1_18: String,
  ctf2_18: String,
  ctf3_18: String,
  ctf1_19: String,
  ctf2_19: String,
  ctf3_19: String,
  ctf1_20: String,
  ctf2_20: String,
  ctf3_20: String,

  // J1 and J2 fields
  j1_dip_clearance: String,
  j2_dip_clearance: String,
  j1_contact_pressure_1000a: String,
  j2_contact_pressure_1000a: String,
  j1_contact_pressure_1500a: String,
  j2_contact_pressure_1500a: String,
  j1_aux_contact_pressure: String,
  j2_aux_contact_pressure: String,
  j1_aux_contact_gap: String,
  j2_aux_contact_gap: String,
  j1_forward_coil: String,
  j2_forward_coil: String,
  j1_reverse_coil: String,
  j2_reverse_coil: String,
  j1_min_operating_pressure: String,
  j2_min_operating_pressure: String,
  j1_double_roll_pin: String,
  j2_double_roll_pin: String,
  j1_brass_roller: String,
  j2_brass_roller: String,
  j1_drum_check: String,
  j2_drum_check: String,
  j1_varnish: String,
  j2_varnish: String,
  j1_finger_wear: String,
  j2_finger_wear: String,
  j1_aux_contact_operation: String,
  j2_aux_contact_operation: String,
  j1_contact_to_earth: String,
  j2_contact_to_earth: String,
  j1_contact_to_contact: String,
  j2_contact_to_contact: String,
  j1_coil_to_earth: String,
  j2_coil_to_earth: String,
  j1_ep_valve_leakage: String,
  j2_ep_valve_leakage: String,
  j1_servomotor_leakage: String,
  j2_servomotor_leakage: String,
  j1_switch_operation: String,
  j2_switch_operation: String,

  // L-series serial numbers
  sl_no_l1: String,
  sl_no_l2: String,
  sl_no_l3: String,
  sl_no_l4: String,
  sl_no_l5: String,
  sl_no_l6: String,
  sl_no_c145: String,
  sl_no_c118: String,

  // Check components
  check_components_l1: String,
  check_components_l2: String,
  check_components_l3: String,
  check_components_l4: String,
  check_components_l5: String,
  check_components_l6: String,
  check_components_c145: String,
  check_components_c118: String,

  // Coil resistance
  coil_resistance_l1: String,
  coil_resistance_l2: String,
  coil_resistance_l3: String,
  coil_resistance_l4: String,
  coil_resistance_l5: String,
  coil_resistance_l6: String,
  coil_resistance_c145: String,
  coil_resistance_c118: String,

  // Contact gap
  contact_gap_l1: String,
  contact_gap_l2: String,
  contact_gap_l3: String,
  contact_gap_l4: String,
  contact_gap_l5: String,
  contact_gap_l6: String,
  contact_gap_c145: String,
  contact_gap_c118: String,

  // Contact pressure
  contact_pressure_l1: String,
  contact_pressure_l2: String,
  contact_pressure_l3: String,
  contact_pressure_l4: String,
  contact_pressure_l5: String,
  contact_pressure_l6: String,
  contact_pressure_c145: String,
  contact_pressure_c118: String,

  // Air pressure
  air_pressure_l1: String,
  air_pressure_l2: String,
  air_pressure_l3: String,
  air_pressure_l4: String,
  air_pressure_l5: String,
  air_pressure_l6: String,
  air_pressure_c145: String,
  air_pressure_c118: String,

  // Voltage
  voltage_l1: String,
  voltage_l2: String,
  voltage_l3: String,
  voltage_l4: String,
  voltage_l5: String,
  voltage_l6: String,
  voltage_c145: String,
  voltage_c118: String,

  // Lubrication
  lubrication_l1: String,
  lubrication_l2: String,
  lubrication_l3: String,
  lubrication_l4: String,
  lubrication_l5: String,
  lubrication_l6: String,
  lubrication_c145: String,
  lubrication_c118: String,

  air_leakage: String,

  // Coil energies
  coil_energies_l1: String,
  coil_energies_l2: String,
  coil_energies_l3: String,
  coil_energies_l4: String,
  coil_energies_l5: String,
  coil_energies_l6: String,
  coil_energies_c145: String,
  coil_energies_c118: String,

  // Coil deenergies
  coil_deenergies_l1: String,
  coil_deenergies_l2: String,
  coil_deenergies_l3: String,
  coil_deenergies_l4: String,
  coil_deenergies_l5: String,
  coil_deenergies_l6: String,
  coil_deenergies_c145: String,
  coil_deenergies_c118: String,

  // Shunt
  shunt_l1: String,
  shunt_l2: String,
  shunt_l3: String,
  shunt_l4: String,
  shunt_l5: String,
  shunt_l6: String,
  shunt_c145: String,
  shunt_c118: String,

  // Interlock
  interlock_l1: String,
  interlock_l2: String,
  interlock_l3: String,
  interlock_l4: String,
  interlock_l5: String,
  interlock_l6: String,
  interlock_c145: String,
  interlock_c118: String,

  // Arc chute
  arc_chute_l1: String,
  arc_chute_l2: String,
  arc_chute_l3: String,
  arc_chute_l4: String,
  arc_chute_l5: String,
  arc_chute_l6: String,
  arc_chute_c145: String,
  arc_chute_c118: String,

  insulation_resistance: String,

  // Bus bar earth
  bus_bar_earth_l1: String,
  bus_bar_earth_l2: String,
  bus_bar_earth_l3: String,
  bus_bar_earth_l4: String,
  bus_bar_earth_l5: String,
  bus_bar_earth_l6: String,
  bus_bar_earth_c145: String,
  bus_bar_earth_c118: String,

  // Contact to contact
  contact_to_contact_l1: String,
  contact_to_contact_l2: String,
  contact_to_contact_l3: String,
  contact_to_contact_l4: String,
  contact_to_contact_l5: String,
  contact_to_contact_l6: String,
  contact_to_contact_c145: String,
  contact_to_contact_c118: String,

  // Coil earth
  coil_earth_l1: String,
  coil_earth_l2: String,
  coil_earth_l3: String,
  coil_earth_l4: String,
  coil_earth_l5: String,
  coil_earth_l6: String,
  coil_earth_c145: String,
  coil_earth_c118: String,

  // Arc chute locking
  arc_chute_locking_l1: String,
  arc_chute_locking_l2: String,
  arc_chute_locking_l3: String,
  arc_chute_locking_l4: String,
  arc_chute_locking_l5: String,
  arc_chute_locking_l6: String,
  arc_chute_locking_c145: String,
  arc_chute_locking_c118: String,

  // Endurance test
  endurance_test_l1: String,
  endurance_test_l2: String,
  endurance_test_l3: String,
  endurance_test_l4: String,
  endurance_test_l5: String,
  endurance_test_l6: String,
  endurance_test_c145: String,
  endurance_test_c118: String,

  // S-series serial numbers
  s11_serial: String,
  s12_serial: String,
  s13_serial: String,
  s14_serial: String,
  s21_serial: String,
  s22_serial: String,
  s23_serial: String,
  s24_serial: String,

  // S-series components
  s11_components: String,
  s12_components: String,
  s13_components: String,
  s14_components: String,
  s21_components: String,
  s22_components: String,
  s23_components: String,
  s24_components: String,

  // S-series contact gap
  s11_contact_gap: String,
  s12_contact_gap: String,
  s13_contact_gap: String,
  s14_contact_gap: String,
  s21_contact_gap: String,
  s22_contact_gap: String,
  s23_contact_gap: String,
  s24_contact_gap: String,

  // S-series contact pressure
  s11_contact_pressure: String,
  s12_contact_pressure: String,
  s13_contact_pressure: String,
  s14_contact_pressure: String,
  s21_contact_pressure: String,
  s22_contact_pressure: String,
  s23_contact_pressure: String,
  s24_contact_pressure: String,

  // S-series air pressure
  s11_air_pressure: String,
  s12_air_pressure: String,
  s13_air_pressure: String,
  s14_air_pressure: String,
  s21_air_pressure: String,
  s22_air_pressure: String,
  s23_air_pressure: String,
  s24_air_pressure: String,

  // S-series voltage
  s11_voltage: String,
  s12_voltage: String,
  s13_voltage: String,
  s14_voltage: String,
  s21_voltage: String,
  s22_voltage: String,
  s23_voltage: String,
  s24_voltage: String,

  // S-series lubrication
  s11_lubrication: String,
  s12_lubrication: String,
  s13_lubrication: String,
  s14_lubrication: String,
  s21_lubrication: String,
  s22_lubrication: String,
  s23_lubrication: String,
  s24_lubrication: String,

  air_leakage_all: String,

  // S-series coil energized
  s11_coil_energized: String,
  s12_coil_energized: String,
  s13_coil_energized: String,
  s14_coil_energized: String,
  s21_coil_energized: String,
  s22_coil_energized: String,
  s23_coil_energized: String,
  s24_coil_energized: String,

  // S-series coil deenergized
  s11_coil_deenergized: String,
  s12_coil_deenergized: String,
  s13_coil_deenergized: String,
  s14_coil_deenergized: String,
  s21_coil_deenergized: String,
  s22_coil_deenergized: String,
  s23_coil_deenergized: String,
  s24_coil_deenergized: String,

  // S-series shunt
  s11_shunt: String,
  s12_shunt: String,
  s13_shunt: String,
  s14_shunt: String,
  s21_shunt: String,
  s22_shunt: String,
  s23_shunt: String,
  s24_shunt: String,

  // S-series arc chute
  s11_arc_chute: String,
  s12_arc_chute: String,
  s13_arc_chute: String,
  s14_arc_chute: String,
  s21_arc_chute: String,
  s22_arc_chute: String,
  s23_arc_chute: String,
  s24_arc_chute: String,

  // Test fields
  test_10: String,
  actual_10: String,

  // S3 and S4 series 10a
  s31_10a: String,
  s32_10a: String,
  s33_10a: String,
  s34_10a: String,
  s41_10a: String,
  s42_10a: String,
  s43_10a: String,
  s44_10a: String,

  // S3 and S4 series 10b
  s31_10b: String,
  s32_10b: String,
  s33_10b: String,
  s34_10b: String,
  s41_10b: String,
  s42_10b: String,
  s43_10b: String,
  s44_10b: String,

  // S3 and S4 series 10c
  s31_10c: String,
  s32_10c: String,
  s33_10c: String,
  s34_10c: String,
  s41_10c: String,
  s42_10c: String,
  s43_10c: String,
  s44_10c: String,

  // S3 and S4 series 11
  s31_11: String,
  s32_11: String,
  s33_11: String,
  s34_11: String,
  s41_11: String,
  s42_11: String,
  s43_11: String,
  s44_11: String,

  // S3 and S4 series 12
  s31_12: String,
  s32_12: String,
  s33_12: String,
  s34_12: String,
  s41_12: String,
  s42_12: String,
  s43_12: String,
  s44_12: String,

  // S3 and S4 series 13
  s31_13: String,
  s32_13: String,
  s33_13: String,
  s34_13: String,
  s41_13: String,
  s42_13: String,
  s43_13: String,
  s44_13: String,

  // S3 and S4 series sl_no
  s31_sl_no: String,
  s32_sl_no: String,
  s33_sl_no: String,
  s34_sl_no: String,
  s41_sl_no: String,
  s42_sl_no: String,
  s43_sl_no: String,
  s44_sl_no: String,

  // S3 and S4 series 1-9
  s31_1: String,
  s32_1: String,
  s33_1: String,
  s34_1: String,
  s41_1: String,
  s42_1: String,
  s43_1: String,
  s44_1: String,

  s31_2: String,
  s32_2: String,
  s33_2: String,
  s34_2: String,
  s41_2: String,
  s42_2: String,
  s43_2: String,
  s44_2: String,

  s31_3: String,
  s32_3: String,
  s33_3: String,
  s34_3: String,
  s41_3: String,
  s42_3: String,
  s43_3: String,
  s44_3: String,

  s31_4: String,
  s32_4: String,
  s33_4: String,
  s34_4: String,
  s41_4: String,
  s42_4: String,
  s43_4: String,
  s44_4: String,

  s31_5: String,
  s32_5: String,
  s33_5: String,
  s34_5: String,
  s41_5: String,
  s42_5: String,
  s43_5: String,
  s44_5: String,

  s31_6: String,
  s32_6: String,
  s33_6: String,
  s34_6: String,
  s41_6: String,
  s42_6: String,
  s43_6: String,
  s44_6: String,

  // S3 and S4 series 7a
  s31_7a: String,
  s32_7a: String,
  s33_7a: String,
  s34_7a: String,
  s41_7a: String,
  s42_7a: String,
  s43_7a: String,
  s44_7a: String,

  // S3 and S4 series 7b
  s31_7b: String,
  s32_7b: String,
  s33_7b: String,
  s34_7b: String,
  s41_7b: String,
  s42_7b: String,
  s43_7b: String,
  s44_7b: String,

  s31_8: String,
  s32_8: String,
  s33_8: String,
  s34_8: String,
  s41_8: String,
  s42_8: String,
  s43_8: String,
  s44_8: String,

  s31_9: String,
  s32_9: String,
  s33_9: String,
  s34_9: String,
  s41_9: String,
  s42_9: String,
  s43_9: String,
  s44_9: String,

  // Input fields
  input_1_3: String,
  input_1_4: String,
  input_2_4: String,
  input_2_5: String,
  input_2_6: String,
  input_2_7: String,
  input_2_8: String,
  input_2_9: String,
  input_2_10: String,
  input_2_11: String,
  input_3_4: String,
  input_3_5: String,
  input_3_6: String,
  input_3_7: String,
  input_3_8: String,
  input_3_9: String,
  input_3_10: String,
  input_3_11: String,
  input_4_4: String,
  input_4_5: String,
  input_4_6: String,
  input_4_7: String,
  input_4_8: String,
  input_4_9: String,
  input_4_10: String,
  input_4_11: String,
  input_5_4: String,
  input_5_5: String,
  input_5_6: String,
  input_5_7: String,
  input_5_8: String,
  input_5_9: String,
  input_5_10: String,
  input_5_11: String,
  input_6_4: String,
  input_6_5: String,
  input_6_6: String,
  input_6_7: String,
  input_6_8: String,
  input_6_9: String,
  input_6_10: String,
  input_6_11: String,
  input_7_4: String,
  input_7_5: String,
  input_7_6: String,
  input_7_7: String,
  input_7_8: String,
  input_7_9: String,
  input_7_10: String,
  input_7_11: String,

  // CTF and Reverser fields
  ctf1: String,
  ctf2: String,
  ctf3: String,
  reverser_j1: String,
  reverser_j2: String,

  // EP valve
  ep_valve_ctf1: String,
  ep_valve_ctf2: String,
  ep_valve_ctf3: String,
  ep_valve_j1: String,
  ep_valve_j2: String,

  // Dowel sleeve
  dowel_sleeve_ctf1: String,
  dowel_sleeve_ctf2: String,
  dowel_sleeve_ctf3: String,
  dowel_sleeve_j1: String,
  dowel_sleeve_j2: String,

  // Piston bucket
  piston_bucket_ctf1: String,
  piston_bucket_ctf2: String,
  piston_bucket_ctf3: String,
  piston_bucket_j1: String,
  piston_bucket_j2: String,

  // Finger contact
  finger_contact_ctf1: String,
  finger_contact_ctf2: String,
  finger_contact_ctf3: String,
  finger_contact_j1: String,
  finger_contact_j2: String,

  // Field and Standard fields
  field1: String,
  field2: String,
  field3: String,
  field4: String,
  field5: String,

  // Standard fields with status
  standard_1: String,
  l1_status_1: String,
  l2_status_1: String,
  l3_status_1: String,
  l4_status_1: String,
  l5_status_1: String,
  l6_status_1: String,
  c145_status_1: String,
  c118_status_1: String,

  standard_2: String,
  l1_status_2: String,
  l2_status_2: String,
  l3_status_2: String,
  l4_status_2: String,
  l5_status_2: String,
  l6_status_2: String,
  c145_status_2: String,
  c118_status_2: String,

  standard_3: String,
  l1_status_3: String,
  l2_status_3: String,
  l3_status_3: String,
  l4_status_3: String,
  l5_status_3: String,
  l6_status_3: String,
  c145_status_3: String,
  c118_status_3: String,

  standard_4: String,
  l1_status_4: String,
  l2_status_4: String,
  l3_status_4: String,
  l4_status_4: String,
  l5_status_4: String,
  l6_status_4: String,
  c145_status_4: String,
  c118_status_4: String,

  standard_5: String,
  l1_status_5: String,
  l2_status_5: String,
  l3_status_5: String,
  l4_status_5: String,
  l5_status_5: String,
  l6_status_5: String,
  c145_status_5: String,
  c118_status_5: String,

  standard_6: String,
  l1_status_6: String,
  l2_status_6: String,
  l3_status_6: String,
  l4_status_6: String,
  l5_status_6: String,
  l6_status_6: String,
  c145_status_6: String,
  c118_status_6: String,

  standard_7: String,
  l1_status_7: String,
  l2_status_7: String,
  l3_status_7: String,
  l4_status_7: String,
  l5_status_7: String,
  l6_status_7: String,
  c145_status_7: String,
  c118_status_7: String,

  standard_8: String,
  l1_status_8: String,
  l2_status_8: String,
  l3_status_8: String,
  l4_status_8: String,
  l5_status_8: String,
  l6_status_8: String,
  c145_status_8: String,
  c118_status_8: String,

  // Status fields
  standard_0: String,
  status_0: String,
  status_1: String,
  status_2: String,
  status_3: String,
  status_4: String,
  status_5: String,
  status_6: String,
  status_7: String,
  status_8: String,
  status_9: String,
  status_10: String,

  // Serial standard
  serial_standard: String,

  // Insulation 500V for C-series
  insulation_500v_c101: String,
  insulation_500v_c102: String,
  insulation_500v_c103: String,
  insulation_500v_c105: String,
  insulation_500v_c106: String,
  insulation_500v_c107: String,
  insulation_500v_c108: String,

  // Insulation 1000V for C-series
  insulation_1000v_c101: String,
  insulation_1000v_c102: String,
  insulation_1000v_c103: String,
  insulation_1000v_c105: String,
  insulation_1000v_c106: String,
  insulation_1000v_c107: String,
  insulation_1000v_c108: String,

  // Phase
  phase_c101: String,
  phase_c102: String,
  phase_c103: String,
  phase_c105: String,
  phase_c106: String,
  phase_c107: String,
  phase_c108: String,

  // Phase shaft
  phase_shaft_c101: String,

  phase_shaft_c102: String,
  phase_shaft_c103: String,
  phase_shaft_c105: String,
  phase_shaft_c106: String,
  phase_shaft_c107: String,
  phase_shaft_c108: String,

  // Coil resistance for C-series
  coil_resistance_c101: String,
  coil_resistance_c102: String,
  coil_resistance_c103: String,
  coil_resistance_c105: String,
  coil_resistance_c106: String,
  coil_resistance_c107: String,
  coil_resistance_c108: String,

  // Pickup voltage
  pickup_voltage_c101: String,
  pickup_voltage_c102: String,
  pickup_voltage_c103: String,
  pickup_voltage_c105: String,
  pickup_voltage_c106: String,
  pickup_voltage_c107: String,
  pickup_voltage_c108: String,

  // Dropout voltage
  dropout_voltage_c101: String,
  dropout_voltage_c102: String,
  dropout_voltage_c103: String,
  dropout_voltage_c105: String,
  dropout_voltage_c106: String,
  dropout_voltage_c107: String,
  dropout_voltage_c108: String,

  // Contact pressure 1
  contact_pressure_1_c101: String,
  contact_pressure_1_c102: String,
  contact_pressure_1_c103: String,
  contact_pressure_1_c105: String,
  contact_pressure_1_c106: String,
  contact_pressure_1_c107: String,
  contact_pressure_1_c108: String,

  // Contact pressure 2
  contact_pressure_2_c101: String,
  contact_pressure_2_c102: String,
  contact_pressure_2_c103: String,
  contact_pressure_2_c105: String,
  contact_pressure_2_c106: String,
  contact_pressure_2_c107: String,
  contact_pressure_2_c108: String,

  // Contact pressure 3
  contact_pressure_3_c101: String,
  contact_pressure_3_c102: String,
  contact_pressure_3_c103: String,
  contact_pressure_3_c105: String,
  contact_pressure_3_c106: String,
  contact_pressure_3_c107: String,
  contact_pressure_3_c108: String,

  // Aux contact
  aux_contact_c101: String,
  aux_contact_c102: String,
  aux_contact_c103: String,
  aux_contact_c105: String,
  aux_contact_c106: String,
  aux_contact_c107: String,
  aux_contact_c108: String,

  // Contact gap 1
  contact_gap_1_c101: String,
  contact_gap_1_c102: String,
  contact_gap_1_c103: String,
  contact_gap_1_c105: String,
  contact_gap_1_c106: String,
  contact_gap_1_c107: String,
  contact_gap_1_c108: String,

  // Contact gap 2
  contact_gap_2_c101: String,
  contact_gap_2_c102: String,
  contact_gap_2_c103: String,
  contact_gap_2_c105: String,
  contact_gap_2_c106: String,
  contact_gap_2_c107: String,
  contact_gap_2_c108: String,

  // Contact gap 3
  contact_gap_3_c101: String,
  contact_gap_3_c102: String,
  contact_gap_3_c103: String,
  contact_gap_3_c105: String,
  contact_gap_3_c106: String,
  contact_gap_3_c107: String,
  contact_gap_3_c108: String,

  // Crushing contact 1
  crushing_contact_1_c101: String,
  crushing_contact_1_c102: String,
  crushing_contact_1_c103: String,
  crushing_contact_1_c105: String,
  crushing_contact_1_c106: String,
  crushing_contact_1_c107: String,
  crushing_contact_1_c108: String,

  // Crushing contact 2
  crushing_contact_2_c101: String,
  crushing_contact_2_c102: String,
  crushing_contact_2_c103: String,
  crushing_contact_2_c105: String,
  crushing_contact_2_c106: String,
  crushing_contact_2_c107: String,
  crushing_contact_2_c108: String,

  // Crushing contact 3
  crushing_contact_3_c101: String,
  crushing_contact_3_c102: String,
  crushing_contact_3_c103: String,
  crushing_contact_3_c105: String,
  crushing_contact_3_c106: String,
  crushing_contact_3_c107: String,
  crushing_contact_3_c108: String,

  shaft_play: String,

  // Diametrically
  diametrically_c101: String,
  diametrically_c102: String,
  diametrically_c103: String,
  diametrically_c105: String,
  diametrically_c106: String,
  diametrically_c107: String,
  diametrically_c108: String,

  // Laterally
  laterally_c101: String,
  laterally_c102: String,
  laterally_c103: String,
  laterally_c105: String,
  laterally_c106: String,
  laterally_c107: String,
  laterally_c108: String,

  // Aux crushing
  aux_crushing_c101: String,
  aux_crushing_c102: String,
  aux_crushing_c103: String,
  aux_crushing_c105: String,
  aux_crushing_c106: String,
  aux_crushing_c107: String,
  aux_crushing_c108: String,

  // Bedding
  bedding_c101: String,
  bedding_c102: String,
  bedding_c103: String,
  bedding_c105: String,
  bedding_c106: String,
  bedding_c107: String,
  bedding_c108: String,

  lubrication: String,

  // Armature yoke right
  armature_yoke_right_c101: String,
  armature_yoke_right_c102: String,
  armature_yoke_right_c103: String,
  armature_yoke_right_c105: String,
  armature_yoke_right_c106: String,
  armature_yoke_right_c107: String,
  armature_yoke_right_c108: String,

  // Armature yoke left
  armature_yoke_left_c101: String,
  armature_yoke_left_c102: String,
  armature_yoke_left_c103: String,
  armature_yoke_left_c105: String,
  armature_yoke_left_c106: String,
  armature_yoke_left_c107: String,
  armature_yoke_left_c108: String,

  // Additional status fields
  status1: String,
  status11: String,
  status12: String,
  status13: String,
  status14: String,
  status15: String,

  // Reference and actual fields
  ref_actual: String,
  serial_actual: String,
  insulation_500v_actual: String,
  insulation_1000v_actual: String,
  coil_resistance_actual: String,
  pickup_voltage_actual: String,
  contact_gap_actual: String,
  wipe_contact_actual: String,
  aux_contact_actual: String,
  core_armature_actual: String,
  shaft_play_actual: String,
  diametrically_actual: String,
  laterally_actual: String,
  alignment_actual: String,
  bedding_actual: String,
  dropout_voltage_actual: String,
  lubrication_actual: String,
  armature_yoke_actual: String,
  
  
}, {
  timestamps: true
});

module.exports = mongoose.model('panelshopchecksheets', panelShopCheckSheetSchema);