const mongoose = require('mongoose');

const valveCheckSheetSchema = new mongoose.Schema({
  // Header Section
  loco_details: { type: String },
  overhaul_month: { type: String },
  
  // CAGE PANEL Section
  cage_cab1: { type: String },
  cage_cab2: { type: String },
  brake_pressure_cab1: { type: String },
  brake_pressure_cab2: { type: String },
  reduction_cab1: { type: String },
  reduction_cab2: { type: String },
  run_cab1: { type: String },
  run_cab2: { type: String },
  min_reduction_cab1: { type: String },
  min_reduction_cab2: { type: String },
  full_service_cab1: { type: String },
  full_service_cab2: { type: String },
  over_reduction_cab1: { type: String },
  over_reduction_cab2: { type: String },
  emergency_cab1: { type: String },
  emergency_cab2: { type: String },
  leakage_cab1: { type: String },
  leakage_cab2: { type: String },
  complete_valve_cab1: { type: String },
  complete_valve_cab2: { type: String },
  manufacturer_name: { type: String },
  manufacturer_cab1: { type: String },
  manufacturer_cab2: { type: String },
  manufacturing_date: { type: String },
  manufacturing_date_cab1: { type: String },
  manufacturing_date_cab2: { type: String },
  
  // SA-9 Section
  sa9_pressure_cab1: { type: String },
  sa9_pressure_cab2: { type: String },
  sa9_leakage_cab1: { type: String },
  sa9_leakage_cab2: { type: String },
  sa9_rubber_cab1: { type: String },
  sa9_rubber_cab2: { type: String },
  sa9_kit_cab1: { type: String },
  sa9_kit_cab2: { type: String },
  sa9_manufacturing_cab1: { type: String },
  sa9_manufacturing_cab2: { type: String },
  sa9_extra_cab1: { type: String },
  sa9_extra_cab2: { type: String },
  
  // FINE FILTER Section
  filter_condition: { type: String },
  filter_manufacturer_actual: { type: String },
  filter_date_actual: { type: String },
  drain_cock_operation: { type: String },
  filter_leakage: { type: String },
  
  // DUPLEX CHECK VALVE Section
  duplex_operation: { type: String },
  duplex_leakage: { type: String },
  duplex_valve_actual: { type: String },
  manufacturer_actual: { type: String },
  manufacture_date_actual: { type: String },
  
  // FEED VALVE Section
  feed_valve_pressure: { type: String },
  feed_valve_leakage: { type: String },
  rubber_items: { type: String },
  kit_make: { type: String },
  kit_make_actual: { type: String },
  kit_date: { type: String },
  kit_date_actual: { type: String },
  valve_replacement: { type: String },
  body_thread: { type: String },
  
  // AUTO DRAIN VALVE Section
  auto_drain_ref: { type: String },
  auto_drain_rubber: { type: String },
  auto_drain_kit_make: { type: String },
  auto_drain_kit_actual: { type: String },
  auto_drain_date: { type: String },
  auto_drain_date_actual: { type: String },
  auto_drain_leakage: { type: String },
  auto_drain_crack: { type: String },
  
  // C-3W Distributor Valve Section
  c3w_ref: { type: String },
  c3w_rubber: { type: String },
  c3w_kit_make: { type: String },
  c3w_kit_actual: { type: String },
  c3w_date: { type: String },
  c3w_date_actual: { type: String },
  c3w_operation: { type: String },
  c3w_leakage: { type: String },
  c3w_body: { type: String },
  c3w_test_bench: { type: String },
  c3w_soap_leakage: { type: String },
  c3w_goods_app: { type: String },
  c3w_goods_release: { type: String },
  c3w_pass_app: { type: String },
  c3w_pass_release: { type: String },
  
  // RESERVOIR Section
  reservoir_visual: { type: String },
  reservoir_leakage: { type: String },
  
  // AIR FLOW INDICATOR VALVE Section
  air_flow_rubber: { type: String },
  air_flow_make: { type: String },
  air_flow_date: { type: String },
  air_flow_operation: { type: String },
  air_flow_leakage: { type: String },
  air_flow_crack: { type: String },
  air_flow_check: { type: String },
  
  // MU-2B Section
  mu2b_rubber: { type: String },
  mu2b_make: { type: String },
  mu2b_date: { type: String },
  mu2b_crack: { type: String },
  mu2b_port53: { type: String },
  mu2b_port30: { type: String },
  mu2b_port30_trail: { type: String },
  mu2b_port53_exhaust: { type: String },
  mu2b_leakage: { type: String },
  
  // F-1 SELECTOR VALVE Section
  f1_rubber: { type: String },
  f1_make: { type: String },
  f1_date: { type: String },
  f1_crack: { type: String },
  f1_port4_16: { type: String },
  f1_port14: { type: String },
  f1_port14_trail: { type: String },
  f1_port16_20: { type: String },
  f1_leakage: { type: String },
  
  // HORN VALVE Section
  horn_valve_actual_1: { type: String },
  horn_valve_actual_2: { type: String },
  horn_valve_actual_3: { type: String },
  horn_valve_actual_4: { type: String },
  horn_valve_actual_5: { type: String },
  
  // SDW1 RELAY VALVE / R6 RELAY VALVE Section
  relay_valve_actual_1: { type: String },
  relay_valve_actual_2: { type: String },
  relay_valve_actual_3: { type: String },
  relay_valve_actual_4: { type: String },
  relay_valve_actual_5: { type: String },
  relay_valve_actual_6: { type: String },
  relay_valve_actual_7: { type: String },
  relay_valve_actual_8: { type: String },
  relay_valve_actual_9: { type: String },
  relay_valve_actual_10: { type: String },
  relay_valve_actual_11: { type: String },
  relay_valve_actual_12: { type: String },
  relay_valve_actual_13: { type: String },
  relay_valve_actual_14: { type: String },
  
  // Limiting Valve Section
  limiting_valve_actual_1: { type: String },
  limiting_valve_actual_2: { type: String },
  limiting_valve_actual_3: { type: String },
  limiting_valve_actual_4: { type: String },
  limiting_valve_actual_5: { type: String },
  limiting_valve_actual_6: { type: String },
  limiting_valve_actual_7: { type: String },
  prv_spring_actual: { type: String },
  prv_leakage_actual: { type: String },
  prv_pressure_actual: { type: String },
  
  // AUTOMATIC ISOLATING VALVE Section
  aiv_body_actual: { type: String },
  aiv_springs_actual: { type: String },
  aiv_height_actual: { type: String },
  aiv_rubber_actual: { type: String },
  aiv_kit_actual: { type: String },
  aiv_date_actual: { type: String },
  aiv_test_actual: { type: String },
  aiv_air_actual: { type: String },
  
  // DOUBLE CHECK VALVE Section
  dcv_valve_actual: { type: String },
  dcv_mfg_actual: { type: String },
  dcv_date_actual: { type: String },
  dcv_port1_actual: { type: String },
  dcv_port2_actual: { type: String },
  dcv_body_actual: { type: String },
  
  // Angle Cock BP/Angle Cock FP Section
  bp_valve1_actual: { type: String },
  bp_valve2_actual: { type: String },
  bp_mfg1_actual: { type: String },
  bp_mfg2_actual: { type: String },
  bp_date1_actual: { type: String },
  bp_date2_actual: { type: String },
  bp_ref1_actual: { type: String },
  bp_ref2_actual: { type: String },
  bp_handle1_actual: { type: String },
  bp_handle2_actual: { type: String },
  bp_cap1_actual: { type: String },
  bp_cap2_actual: { type: String },
  bp_port1_actual: { type: String },
  bp_port2_actual: { type: String },
  fp_valve1_actual: { type: String },
  fp_valve2_actual: { type: String },
  fp_mfg1_actual: { type: String },
  fp_mfg2_actual: { type: String },
  fp_date1_actual: { type: String },
  fp_date2_actual: { type: String },
  fp_ref1_actual: { type: String },
  fp_ref2_actual: { type: String },
  plug_handle_actual1: { type: String },
  plug_handle_actual2: { type: String },
  cap_joint_actual1: { type: String },
  cap_joint_actual2: { type: String },
  open_end_actual1: { type: String },
  open_end_actual2: { type: String },
  
  // NON RETURN VALVE Section
  nrv_114_status: { type: String },
  nrv_1_status: { type: String },
  nrv_114_mfg: { type: String },
  nrv_1_mfg: { type: String },
  nrv_114_date: { type: String },
  nrv_1_date: { type: String },
  nrv_34_status: { type: String },
  nrv_z_status: { type: String },
  nrv_34_mfg: { type: String },
  nrv_z_mfg: { type: String },
  nrv_34_date: { type: String },
  nrv_z_date: { type: String },
  nrv_34_leak: { type: String },
  nrv_z_leak: { type: String },
  
  // HORN Section
  horn_condition: { type: String },
  horn_diaphragm: { type: String },
  horn_test: { type: String },
  horn_diaphragm_replace1: { type: String },
  horn_diaphragm_replace2: { type: String },
  horn_diaphragm_make1: { type: String },
  horn_diaphragm_make2: { type: String },
  horn_diaphragm_date1: { type: String },
  horn_diaphragm_date2: { type: String },
  elgi_rubber_kit1: { type: String },
  elgi_rubber_kit2: { type: String },
  elgi_spring1: { type: String },
  elgi_spring2: { type: String },
  
  // SAFETY VALVE Section
  safety_body: { type: String },
  safety_spring: { type: String },
  safety_leakage: { type: String },
  safety_blowoff: { type: String },
  safety_closing: { type: String },
  main_reservoir_body: { type: String },
  main_reservoir_spring: { type: String },
  mrv_leakage: { type: String },
  mrv_operation: { type: String },
  mrv_blowoff: { type: String },
  mrv_closing: { type: String },
  arv_body: { type: String },
  arv_spring: { type: String },
  arv_leakage: { type: String },
  arv_operation: { type: String },
  arv_blowoff: { type: String },
  arv_closing: { type: String },
  
  // WIPER SWITCH Section
  ws_modified: { type: String },
  ws_complete: { type: String },
  ws_manufacturer: { type: String },
  ws_date: { type: String },
  
  // WIPER MOTOR Section
  wm_modified: { type: String },
  wm_complete: { type: String },
  wm_manufacturer: { type: String },
  wm_date: { type: String },
  wm_leakage: { type: String },
  
  // DIRT COLLECTOR Section
  dc_status: { type: String },
  dc_condition: { type: String },
  dc_manufacturer: { type: String },
  dc_date: { type: String },
  dc_drain_cock: { type: String },
  dc_leakage: { type: String },
  
  // ISOLATING COCK / DRAIN COCK Section
  ic_number: { type: String },
  ic_half_no_vent: { type: String },
  ic_half_vent: { type: String },
  ic_three_eighth: { type: String },
  ic_three_fourth: { type: String },
  ic_three_fourth_vent: { type: String },
  ic_one: { type: String },
  ic_one_fourth: { type: String },
  ic_one_fourth_vent: { type: String },
  ic_angle_cock: { type: String },
  ic_drain_cock: { type: String },
  
  // THROTTLE VALVE Section
  tv_spring: { type: String },
  tv_body: { type: String },
  tv_rubber: { type: String },
  tv_kit_make: { type: String },
  tv_date: { type: String },
  tv_ref: { type: String },
  tv_leakage: { type: String },
  
  // AIR STRAINER Section
  as_status: { type: String },
  as_half_inch: { type: String },
  as_half_mfr: { type: String },
  as_half_date: { type: String },
  as_three_eighth: { type: String },
  as_three_mfr: { type: String },
  as_three_date: { type: String },
  as_leak_half: { type: String },
  as_leak_three: { type: String },
  
  // D-1 Emergency Brake Valve Section
  d1_1: { type: String },
  d1_2: { type: String },
  d1_check_1: { type: String },
  d1_check_2: { type: String },
  d1_bp_1: { type: String },
  d1_bp_2: { type: String },
  d1_bc_1: { type: String },
  d1_bc_2: { type: String },
  d1_ref_1: { type: String },
  d1_ref_2: { type: String },
  d1_rubber_1: { type: String },
  d1_rubber_2: { type: String },
  d1_kit_1: { type: String },
  d1_kit_2: { type: String },
  d1_date_1: { type: String },
  d1_date_2: { type: String },
  d1_empty_1: { type: String },
  d1_empty_2: { type: String },
  d1_body_1: { type: String },
  d1_body_2: { type: String },
  d1_leak_1: { type: String },
  d1_leak_2: { type: String },
  
  // HEATLESS TWIN TOWER AIR DRYER Section
  ad_status: { type: String },
  ad_press_ftil: { type: String },
  ad_press_kbil: { type: String },
  ad_cycle: { type: String },
  ad_cycle_ftil: { type: String },
  ad_cycle_kbil: { type: String },
  ad_press_drop: { type: String },
  ad_purge: { type: String },
  ad_solenoid: { type: String },
  ad_coil: { type: String },
  ad_coil_ftil: { type: String },
  ad_coil_sil: { type: String },
  ad_coil_kbil: { type: String },
  ad_function: { type: String },
  ad_drain: { type: String },
  ad_humidity: { type: String },
  ad_leak_test: { type: String },
  ad_leak: { type: String },
  ad_muffler: { type: String },
  ad_rdso: { type: String },
  ad_zero: { type: String },
  ad_kit: { type: String },
  ad_kit_date: { type: String },
  ad_orifice_ftil: { type: String },
  ad_orifice_sil: { type: String },
  ad_orifice_kbil: { type: String },
  ad_ref: { type: String },
  
  // C2 Relay Valve Section
  c2_bc: { type: String },
  c2_bp: { type: String },
  c2_body_bc: { type: String },
  c2_body_bp: { type: String },
  c2_mfr_bc: { type: String },
  c2_mfr_bp: { type: String },
  c2_date_bc: { type: String },
  c2_date_bp: { type: String },
  c2_leak_bc: { type: String },
  c2_leak_bp: { type: String },
  c2_op1_bc: { type: String },
  c2_op1_bp: { type: String },
  c2_op2_bc: { type: String },
  c2_op2_bp: { type: String },
  
  // STATUS OF SEASONAL PRECAUTIONS Section
  season_1: { type: String },
  season_2: { type: String },
  
  // SMI Section
  smi_197: { type: String },
  
  // MS Section
  ms_273: { type: String },
  ms_273_rmk: { type: String },
  ms_214: { type: String },
  ms_214_rmk: { type: String },
  ms_349: { type: String },
  ms_349_rmk: { type: String },
  ms_433: { type: String },
  ms_433_rmk: { type: String },
  
  // TC Section
  tc_52: { type: String },
  tc_52_rmk: { type: String },
  tc_53: { type: String },
  tc_53_rmk: { type: String },
  tc_54: { type: String },
  tc_54_rmk: { type: String },
  tc_108: { type: String },
  tc_108_rmk: { type: String },
  tc_94: { type: String },
  tc_94_rmk: { type: String },
  tc_116: { type: String },
  tc_116_rmk: { type: String },
  tc_123: { type: String },
  tc_123_rmk: { type: String },
  
  // REPLACED LIST Section
  remarks_1: { type: String },
  remarks_2: { type: String },
  remarks_3: { type: String },
  remarks_4: { type: String },
  remarks_5: { type: String },
  remarks_6: { type: String },
  remarks_7: { type: String },
  remarks_8: { type: String },
  remarks_9: { type: String },
  remarks_10: { type: String },
  remarks_11: { type: String },
  remarks_12: { type: String },
  remarks_13: { type: String },
  remarks_14: { type: String },
  remarks_15: { type: String },
  remarks_16: { type: String },
  remarks_17: { type: String },
  remarks_18: { type: String },
  remarks_19: { type: String },
  remarks_20: { type: String },
  remarks_21: { type: String },
  remarks_22: { type: String },
  remarks_23: { type: String },
  remarks_24: { type: String },
  remarks_25: { type: String },
  remarks_26: { type: String },
  remarks_27: { type: String },
  remarks_28: { type: String },
  remarks_29: { type: String },
  remarks_30: { type: String },
  remarks_31: { type: String },
  remarks_32: { type: String },
  remarks_33: { type: String },
  remarks_34: { type: String },
  remarks_35: { type: String },
  remarks_36: { type: String },
  remarks_37: { type: String },
  remarks_38: { type: String },
  remarks_39: { type: String },
  remarks_40: { type: String },
  remarks_41: { type: String },
  remarks_42: { type: String },
  remarks_43: { type: String },
  remarks_44: { type: String }
}, {
  timestamps: true
});

module.exports = mongoose.model('valveCheckSheet', valveCheckSheetSchema);